name: Get Commit ID

on:
  push:
    tags:
      - '*'

jobs:
  get-commit-id:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.name 'Anilathmacloudeqs'
        git config --global user.email 'anilathma@cloudeqs.com'
        git config pull.rebase false

    - name: Extract Tag Name
      id: extract_tag
      run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Commit ID
      run: |
        tag="$env:tag"
        echo "Getting commit ID for tag: $tag"
        git fetch --tags
        commitid=$(git rev-list -n 1 $tag)
        echo "Commit ID: $commitid"
        echo "##[set-output name=commit_id;]$commitid"
      id: get_commit_id

    - name: Display Commit ID
      run: |
        echo "Commit ID is ${{ steps.get_commit_id.outputs.commit_id }}"
