name: Automatic PowerShell Workflow

on:
  push:
    tags:
      - 'p1.0'  # Set the specific tag name you want to trigger the workflow on

jobs:
  get_commit_id_a:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PowerShell script
        run: |
          pwsh -File newshell.ps1 -SourceTag ${{ github.event.ref }}
        shell: pwsh
