name: Get Commit ID

on:
  push:
    branches:
      - main

jobs:
  get_commit_id:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Make the script executable
        run: chmod +x get_commit_id.sh
        working-directory: ${{ github.workspace }}

      - name: Run the script
        run: ./get_commit_id.sh
        working-directory: ${{ github.workspace }}
