name: Get Commit ID2

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  get-commit-id:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up PowerShell
      run: |
        git config --global user.name 'Anilathmacloudeqs'
        git config --global user.email 'anilathma@cloudeqs.com'
        git config pull.rebase false

        # Install Git if not available
        choco install git -y

        echo "##change Executing git pull on $env:SourceTag"
        git pull origin $env:SourceTag --allow-unrelated-histories

        echo "Getting commit id for $env:SourceTag"
        $commitid = (git log -n 1 --pretty=format:"%H")

        echo "Commit ID: $commitid"

        # Set the commit id as an environment variable
        $env:COMMIT_ID = $commitid

    - name: Display Commit ID
      run: echo "Commit ID is $env:COMMIT_ID"
