name: Automatic Python and PowerShell Workflows

on:
  push:
    tags:
      - 'p1.0'  # Set the specific tag name you want to trigger the workflow on

env:
  COMMIT_ID: ${{ github.sha }}

jobs:
  get_commit_id_ani:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: GetCommitIdtest
        run: |
          pwsh -File getcommitid.ps1 -SourceTag ${{ github.event.ref }}
        shell: pwsh
